export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const WATCH_PRODUCT = "WATCH_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_ITEM = "INCREASE_ITEM";
export const DECREASE_ITEM = "DECREASE_ITEM";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const DELETE_FROM_WISHLIST = "DELETE_FROM_WISHLIST";
export const SET_MESSAGE = "SET_MESSAGE";
export const UPDATE_CART_FROM_LOCALSTORAGE = "UPDATE_CART_FROM_LOCALSTORAGE";
export const UPDATE_WISHLIST_FROM_LOCALSTORAGE =
  "UPDATE_WISHLIST_FROM_LOCALSTORAGE";
